# Generated by Django 4.2.7 on 2023-11-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='total_pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='pontualidade',
            field=models.CharField(max_length=50),
        ),
    ]
