# Generated by Django 4.2.7 on 2023-11-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0002_servidor_total_pontos_alter_servidor_pontualidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='total_pontos',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
