# Generated by Django 4.2.7 on 2023-11-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0003_alter_servidor_total_pontos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='total_pontos',
            field=models.IntegerField(default=0),
        ),
    ]
