# Generated by Django 4.2.7 on 2023-11-06 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0004_alter_servidor_total_pontos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diretor_coordenador', models.CharField(max_length=100)),
                ('tarefas', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cad_serv.servidor')),
            ],
        ),
    ]
