# Generated by Django 4.2.7 on 2023-11-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0005_tarefarealizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefarealizada',
            name='colaborador',
            field=models.CharField(max_length=100),
        ),
    ]
