# Generated by Django 4.2.7 on 2023-11-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0006_alter_tarefarealizada_colaborador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='assiduidade',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='atendimento_servicos',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='escala',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='execucao_tarefas',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='iniciativa',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='pontualidade',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='total_pontos',
        ),
    ]
