# Generated by Django 4.2.7 on 2023-11-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0007_remove_servidor_assiduidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='assiduidade',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='servidor',
            name='atendimento_servicos',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='servidor',
            name='escala',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='servidor',
            name='execucao_tarefas',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='servidor',
            name='iniciativa',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='servidor',
            name='matricula',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='servidor',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servidor',
            name='pontualidade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='servidor',
            name='total_pontos',
            field=models.IntegerField(default=0),
        ),
    ]
