# Generated by Django 4.2.7 on 2023-11-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0009_alter_servidor_assiduidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='escala',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=50),
        ),
    ]
