# Generated by Django 4.2.7 on 2023-11-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0010_alter_servidor_escala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='matricula',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='pontualidade',
            field=models.CharField(choices=[('Sem Justificativa', 'Sem Justificativa'), ('2 justificativas', '2 Justificativas'), ('3 justificativas', '3 Justificativas'), ('5 justificativas', '5 Justificativas')], max_length=50),
        ),
    ]
