# Generated by Django 4.2.7 on 2023-11-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0011_alter_servidor_matricula_alter_servidor_pontualidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='assiduidade',
            field=models.CharField(choices=[('Sem Faltas', 'Sem Faltas'), ('1 Falta', '1 Falta'), ('2 Faltas', '2 Faltas'), ('3 Faltas', '3 Faltas')], max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='atendimento_servicos',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='escala',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='execucao_tarefas',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='iniciativa',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='pontualidade',
            field=models.CharField(choices=[('Sem Justificativa', 'Sem Justificativa'), ('2 Justificativas', '2 Justificativas'), ('3 Justificativas', '3 Justificativas'), ('5 Justificativas', '5 Justificativas')], max_length=50),
        ),
    ]
