# Generated by Django 5.0 on 2023-12-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0012_alter_servidor_assiduidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='matricula',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
