# Generated by Django 5.0 on 2023-12-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0014_alter_servidor_escala'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='gratificacao_pontos',
            field=models.IntegerField(default=0),
        ),
    ]
