# Generated by Django 5.0 on 2023-12-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0016_servidor_tipo_escala'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='tipo_modalidade',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto')], default='', max_length=10),
        ),
    ]
