# Generated by Django 5.0 on 2023-12-20 11:13

import app_cad_serv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0018_servidor_mes_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='matricula',
            field=models.CharField(default='', max_length=10, unique=True, validators=[app_cad_serv.models.Servidor.validar_matricula]),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='nome',
            field=models.CharField(default='', max_length=100, validators=[app_cad_serv.models.Servidor.validar_nome]),
        ),
    ]
