# Generated by Django 5.0 on 2024-01-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0020_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'Um usuário com este nome de usuário já existe.'}, help_text='Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.', max_length=150, unique=True, verbose_name='usuário'),
        ),
    ]
