# Generated by Django 5.0 on 2024-01-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0021_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_superusuario',
            field=models.BooleanField(default=False),
        ),
    ]
