# Generated by Django 5.0 on 2024-01-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0023_alter_usuario_groups_alter_usuario_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='ano_referencia',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='assiduidade',
            field=models.CharField(choices=[('Sem Faltas', 'Sem Faltas'), ('1 Falta', '1 Falta'), ('2 Faltas', '2 Faltas'), ('3 Faltas', '3 Faltas')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='atendimento_servicos',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='escala',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='execucao_tarefas',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='iniciativa',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='mes_referencia',
            field=models.CharField(choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Março'), ('4', 'Abril'), ('5', 'Maio'), ('6', 'Junho'), ('7', 'Julho'), ('8', 'Agosto'), ('9', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='pontualidade',
            field=models.CharField(choices=[('Sem Justificativa', 'Sem Justificativa'), ('2 Justificativas', '2 Justificativas'), ('3 Justificativas', '3 Justificativas'), ('5 Justificativas', '5 Justificativas')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='tipo_modalidade',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto')], default='1', max_length=10),
        ),
    ]
