# Generated by Django 5.0 on 2024-01-10 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0024_servidor_ano_referencia_alter_servidor_assiduidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='mes_referencia',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
