# Generated by Django 5.0 on 2024-01-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0025_alter_servidor_mes_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='ano_referencia',
        ),
    ]
