# Generated by Django 5.0 on 2024-01-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0026_remove_servidor_ano_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='setor',
            field=models.CharField(choices=[('Ti', 'Ti'), ('Rh', 'Rh')], default='', max_length=100),
        ),
    ]
