# Generated by Django 5.0 on 2024-01-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0027_servidor_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='servidor',
            name='setor',
            field=models.CharField(choices=[('TI', 'TI'), ('RH', 'RH')], default='', max_length=100),
        ),
    ]
