# Generated by Django 5.0 on 2024-01-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0031_alter_servidor_assiduidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='assiduidade',
            field=models.CharField(choices=[('10', '10'), ('08', '08'), ('04', '04'), ('02', '02')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='atendimento_servicos',
            field=models.CharField(choices=[('30', '30'), ('20', '20'), ('15', '15'), ('10', '10')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='execucao_tarefas',
            field=models.CharField(choices=[('30', '30'), ('20', '20'), ('15', '15'), ('10', '10')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='iniciativa',
            field=models.CharField(choices=[('20 ', '20'), ('15', '15'), ('10', '10'), ('05', '05')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='pontualidade',
            field=models.CharField(choices=[('10', '10'), ('08', '08'), ('04', '04'), ('02', '02')], default='1', max_length=50),
        ),
    ]
