# Generated by Django 5.0 on 2024-01-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0032_alter_servidor_assiduidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='assiduidade',
            field=models.CharField(choices=[('10 Pontos', '10 Pontos'), ('08 Pontos', '08 Pontos'), ('04 Pontos', '04 Pontos'), ('02 Pontos', '02 Pontos')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='atendimento_servicos',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Otimo', 'Ótimo'), ('Bom', 'Bom'), ('Regular', 'Regular')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='execucao_tarefas',
            field=models.CharField(choices=[('30 Pontos', '30 Pontos'), ('20 Pontos', '20 Pontos'), ('15 Pontos', '15 Pontos'), ('10 Pontos', '10 Pontos')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='iniciativa',
            field=models.CharField(choices=[('20 Pontos', '20 Pontos'), ('15 Pontos', '15 Pontos'), ('10 Pontos', '10 Pontos'), ('05 Pontos', '05 Pontos')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='pontualidade',
            field=models.CharField(choices=[('10 Pontos', '10 Pontos'), ('08 Pontos', '08 Pontos'), ('04 Pontos', '04 Pontos'), ('02 Pontos', '02 Pontos')], default='1', max_length=50),
        ),
    ]
