# Generated by Django 5.0 on 2024-01-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0033_alter_servidor_assiduidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='atendimento_servicos',
            field=models.CharField(choices=[('20 Pontos', '20 Pontos'), ('15 Pontos', '15 Pontos'), ('10 Pontos', '10 Pontos'), ('05 Pontos', '05 Pontos')], default='1', max_length=10),
        ),
    ]
