# Generated by Django 5.0 on 2024-01-24 12:51

import app_cad_serv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0035_alter_servidor_assiduidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='pessoa_mat',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='matricula',
            field=models.CharField(blank=True, default='', max_length=10, unique=True, validators=[app_cad_serv.models.Servidor.validar_matricula]),
        ),
    ]
