# Generated by Django 5.0 on 2024-02-01 12:23

import app_cad_serv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0036_alter_pessoa_pessoa_mat_alter_servidor_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='matricula',
            field=models.CharField(blank=True, default='', max_length=10, validators=[app_cad_serv.models.Servidor.validar_matricula]),
        ),
    ]
