# Generated by Django 5.0 on 2024-02-01 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0038_alter_servidor_escala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='assiduidade',
            field=models.CharField(choices=[('', ''), ('10', '10'), ('08', '08'), ('04', '04'), ('02', '02')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='atendimento_servicos',
            field=models.CharField(choices=[('', ''), ('20', '20'), ('15', '15'), ('10', '10'), ('05', '05')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='escala',
            field=models.CharField(choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='blank', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='execucao_tarefas',
            field=models.CharField(choices=[('', ''), ('30', '30'), ('20', '20'), ('15', '15'), ('10', '10')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='iniciativa',
            field=models.CharField(choices=[('', ''), ('20', '20'), ('15', '15'), ('10', '10'), ('05', '05')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='pontualidade',
            field=models.CharField(choices=[('', ''), ('10', '10'), ('08', '08'), ('04', '04'), ('02', '02')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='setor',
            field=models.CharField(choices=[('', ''), ('T.I', 'T.I'), ('RH', 'RH')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='tipo_escala',
            field=models.CharField(choices=[('', ''), ('DIRETA', 'Direta'), ('INDIRETA', 'Indireta')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='tipo_modalidade',
            field=models.CharField(choices=[('', ''), ('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarefarealizada',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cad_serv.servidor'),
        ),
    ]
