# Generated by Django 5.0 on 2024-02-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0040_alter_tarefarealizada_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefarealizada',
            name='colaborador',
            field=models.CharField(max_length=150),
        ),
    ]
