# Generated by Django 5.0 on 2024-02-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0041_alter_tarefarealizada_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefarealizada',
            name='servidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_cad_serv.servidor'),
            preserve_default=False,
        ),
    ]
