# Generated by Django 5.0 on 2024-02-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0042_tarefarealizada_servidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefarealizada',
            name='servidor',
        ),
    ]
