# Generated by Django 5.0 on 2024-02-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0045_alter_tarefarealizada_colaborador'),
    ]

    operations = [
    ]
