# Generated by Django 5.0 on 2024-02-08 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0048_tarefarealizada_colaborador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefarealizada',
            name='colaborador',
        ),
        migrations.AddField(
            model_name='tarefarealizada',
            name='servidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cad_serv.servidor'),
        ),
    ]
