# Generated by Django 5.0 on 2024-02-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0049_remove_tarefarealizada_colaborador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='setor',
            field=models.CharField(choices=[('', ''), ('T.I', 'T.I'), ('RH', 'RH'), ('CAF', 'CAF')], default='', max_length=100),
        ),
    ]
