# Generated by Django 5.0 on 2024-03-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0051_alter_servidor_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='tarefas',
            field=models.TextField(default=1),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='setor',
            field=models.CharField(choices=[('', ''), ('Apoio Atendimento', 'Apoio Atendimento'), ('Arrecadação', 'Arrecadação'), ('ASCOM', 'ASCOM'), ('Cadastro Imobiliário', 'Cadastro Imobiliário'), ('Cadastro Mercantil', 'Cadastro Mercantil'), ('CAF', 'CAF'), ('Catraca', 'Catraca'), ('Cont e convênios', 'Cont e convênios'), ('Coord Geral da rec', 'Coord Geral da rec'), ('CTIT', 'CTIT'), ('Digitalização CTIT', 'Digitalização CTIT'), ('Diret Atend Contri', 'Diretoria do Atendimento ao Contribuente'), ('Diret Rec Mun', 'Diret Rec Mun'), ('Diretoria ADM', 'Diretoria ADM'), ('DTM', 'DTM'), ('Gab Orçamento', 'Gabinete Orçamento'), ('Geoprocessamento', 'Geoprocessamento'), ('Inteligência fiscal', 'Inteligência fiscal'), ('ITBI', 'ITBI'), ('Orçamento', 'Orçamento'), ('RH', 'RH'), ('Subsec Rec Mun', 'Subsecretaria Rec Mun'), ('Superintendência', 'Superintendência'), ('Triagem', 'Triagem'), ('UGOCC', 'UGOCC')], default='', max_length=100),
        ),
    ]
