# Generated by Django 5.0 on 2024-03-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0053_remove_servidor_tarefas'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='teste_tarefa',
            field=models.TextField(default=''),
        ),
    ]
