# Generated by Django 5.0 on 2024-03-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0054_servidor_teste_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='teste_tarefa',
        ),
    ]
