# Generated by Django 5.0 on 2024-03-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0055_remove_servidor_teste_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='teste_tarefas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
