# Generated by Django 5.0 on 2024-06-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0057_alter_servidor_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pdfs/'),
        ),
    ]
